# Generated by Django 2.2 on 2020-12-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_species', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='typeOfProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_Of_Illness', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(height_field=675, upload_to=None, width_field=900)),
                ('name', models.CharField(max_length=255)),
                ('indenty', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=1000)),
                ('kind_Of_Illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.typeOfProblem')),
                ('name_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.species')),
            ],
        ),
    ]
