# Generated by Django 2.2 on 2020-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='typeOfProblem',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='kind_Of_Illness',
            new_name='kind_Of_issue',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='kind_Of_Illness',
            new_name='kind_Of_Issue',
        ),
        migrations.AlterField(
            model_name='tree',
            name='picture',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
