# Generated by Django 2.2 on 2020-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20201210_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
    ]
