# Generated by Django 2.2 on 2020-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20201210_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
